include $(OPENMRNPATH)/etc/mbed.mk
CORECFLAGS += -DTARGET_LPC2368
INCLUDES += \
	-I"$(MBEDPATH)/mbed/vendor/NXP/capi" \
	-I"$(MBEDPATH)/mbed/vendor/NXP/capi/LPC2368" \
	-I"$(MBEDPATH)/mbed/vendor/NXP/cmsis/LPC2368"

include $(OPENMRNPATH)/etc/applib.mk

