#ifndef _ACC_TIVA_3_HARDWARE_HXX_
#define _ACC_TIVA_3_HARDWARE_HXX_

#define LED_GREEN GPIO_PORTD_BASE, GPIO_PIN_5
#define LED_BLUE GPIO_PORTG_BASE, GPIO_PIN_1
#define LED_YELLOW GPIO_PORTB_BASE, GPIO_PIN_0

#endif // _ACC_TIVA_3_HARDWARE_HXX_
