

#ifndef _BRACZ_CS_TIVASMALL_HARDWARE_HXX_
#define _BRACZ_CS_TIVASMALL_HARDWARE_HXX_

#define LED_RED GPIO_PORTF_BASE, GPIO_PIN_1
#define LED_GREEN GPIO_PORTF_BASE, GPIO_PIN_3
#define LED_BLUE GPIO_PORTF_BASE, GPIO_PIN_2

#endif // _BRACZ_CS_TIVASMALL_HARDWARE_HXX_
